import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';

import './globals.css';
import './theme.css';
import { GlobalNavigation } from 'lib';
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <GlobalNavigation
          customLogo={(<Image src="/ameerAvatar.png" alt="Ameer Logo" width={25} height={25} />)}
          navItems={[
            {
              title: 'User Settings',
              link: '#',
              customComponent: (
                <Link href="/userSettings">User Settings</Link>
              )
            },
            {
              title: 'News Feed',
              link: '#',
              customComponent: (
                <Link href="/newsFeed">News Feed</Link>
              )
            },
            {
              title: 'Widget Dashboard',
              link: '#',
              customComponent: (
                <Link href="/widgetDashboard">Widget Dashboard</Link>
              )
            }
          ]}
        />
        {children}
      </body>
    </html>
  );
}
